a = input("Enter your name: ")
b = input ("Enter your Age: ")
c = input("Enter your favorite language: ")
d = input("Enter your dream company: ")
print ("Hey", a, "as you are",b,"years of age and aspire to work as a",c ,"programmer in",d ,"company you have to put in work! All the best.")